controllers:
    resource: ../src/Controller/
    type: annotation
    defaults:
        index:
            path: /login
            controller: App\Controller\SecurityController::login
kernel:
    resource: ../src/Kernel.php
    type: annotation


